name: Stock Alert Bot

on:
  schedule:
    # 1. Runs every 5 mins from 14:30 to 14:55 UTC (9:30 AM - 9:55 AM EST)
    - cron: '30-55/5 14 * * 1-5'
    
    # 2. Runs every 5 mins from 15:00 to 21:00 UTC (10:00 AM - 4:00 PM EST)
    - cron: '*/5 15-21 * * 1-5'
  
  workflow_dispatch: # This allows you to run it manually for testing 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Fixed to 3.12

      - name: Install Dependencies
        run: pip install alpaca-py pandas_ta requests

      - name: Run Alert Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
